<?php
/**
 *portofoon default Cms portofoon_child-first template.
 * @author Ivan Havryliuk ivan.havryliuk95@gmail.com.
 * @copyright 2020 worzewolf.
 */
?>
<div class="funny-mobile-logo">
    <img class="active-image" src="<?php echo $this->getViewFileUrl('Magento_Cms::images/Vector-logo.png'); ?>" alt="vector mobile">
</div>
<div class="info-block child">
    <h3 class="child-heading"><?= __('Good to know'); ?></h3>
    <p class="child-content"><?= __('If you are satisfied with the ordering process, please like our Facebook page or leave a review, so you also have the chance to win a nice gift voucher worth € 100, - Would you like to stay informed of the latest news and special offers then sign up for our newsletter.'); ?></p>
</div>
<div class="info-block child">
    <h3 class="child-heading"><?= __('What is going to happen now?'); ?></h3>
    <p class="child-content"><?= __('You have received a confirmation of your order by email with Order number [order number]. If you have placed and paid for the order on a working day before 5 p.m., we will start immediately to ensure that you have it at home tomorrow. If you have any questions about the order, please contact us on 0512 - 745293 or send us an email to info@portofoonweb.nl.'); ?></p>
</div>
<div class="info-block child">
    <h3 class="child-heading"><?= __('Did you know that?'); ?></h3>
    <p class="child-content"><?= __('Walkie-talkieWEB has recently introduced a phenomenal new technique called Smart Walkie-talkies. A walkie-talkie system with unprecedented possibilities and unlimited range! Click on this link for more information.'); ?></p>
</div>
